language: c++

addons:
  apt:
    packages:
     - cmake
     - qtbase5-dev
     - libqt5opengl5-dev
     - libboost-dev
     - libboost-regex-dev
     - libboost-system-dev
     - libboost-program-options-dev
     - libeigen3-dev
     - libmysqlclient-dev
     - libmysql++-dev
     - libsqlite3-dev
     - liblog4cpp5-dev
     - libgdal-dev
     - libtinyxml2-dev
     - libarchive-dev
     - libjsoncpp-dev

compiler:
 - gcc
 - clang

script:
 - mkdir build
 - cd build
 - cmake ..
 - cmake --build . -- -j2

